networks:
  traefik:
    name: traefik_proxy

services:
  traefik:
    image: traefik:v3.1.4
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - '--providers.docker.watch=true'
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=vladislav.evst.94@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - "443:443"
      - "80:80"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_proxy"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - traefik