services:
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    extra_hosts:
      - "host.docker.internal:host-gateway"