services:
  scaling-app:
    container_name: scaling-app
    restart: unless-stopped
    build:
      dockerfile: ../infra/Dockerfile
      context: ../app
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mongo:
    container_name: mongo
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    extra_hosts:
      - "host.docker.internal:host-gateway"